bugfix(docs_links): open external URL in browser window, remove depre…
usebruno/bruno pull request #1176
Opened 2023-12-07 14:13 UTC by bpoulaindev

…cated method in electron, refactor to index.tsx

# Description

Open external links in browser window instead of inside Bruno, referencing issue  #1156 

https://github.com/usebruno/bruno/assets/64689165/50c1d58e-188a-4dac-b96a-cda034761913

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

2023-12-07 16:54 UTC, helloanoop commented
@bpoulaindev Changes look good!

I would like you to 1 change.
Can you revert the `.tsx` back to `.js` ?

Still haven't finalised on [typescript migration](https://github.com/usebruno/bruno/discussions/555)
There is also a discussion on [jsdocs](https://github.com/usebruno/bruno/discussions/1168)

Main things stopping from making a decision
* I am worried changing some files to `.tsx` might affect some of our existing PR's (75 of them as of this writing)
* My typescript proficiency is "beginner". At the current stage of Bruno, It would not be wise to for me (as Bruno's lead maintainer) to move to typescript, specially when I am still a beginner.

This is not to say that we will never consider typescript, Its just that I would like to take more time to make a decision.

Thank you for understanding :)

2023-12-07 17:00 UTC, bpoulaindev commented
Can i at least keep it in `.jsx` format instead of `.js` ?

2023-12-07 17:06 UTC, helloanoop commented
> Can i at least keep it in .jsx format instead of .js ?

Sure @bpoulaindev !

2023-12-07 17:12 UTC, bpoulaindev commented
Done 👌

2023-12-07 18:18 UTC, Its-treason requested changes

2023-12-07 18:18 UTC, Its-treason commented on packages/bruno-app/src/components/MarkDown/index.jsx
> +    console.log(event);
```suggestion
```
I think console.log got lost here, can you remove it?

2023-12-19 08:19 UTC, Wapax commented
Hi there ! When will this PR be committed for production, please ?

2023-12-19 08:57 UTC, bpoulaindev commented
> Hi there ! When will this PR be committed for production, please ?

Good question @helloanoop @Its-treason

2023-12-19 18:53 UTC, merged

2023-12-19 18:53 UTC, helloanoop commented
Merged! Thank you @bpoulaindev and @Its-treason !