feat: OpenAPI import: create a default environment
usebruno/bruno pull request #1240
Opened 2023-12-18 21:20 UTC by AndrejsK

# Description

Fixes #1239

The previous solution constructed a default server baseUrl and directly concatenated it into each request of the collection. This makes it difficult to change it later through the UI if it is wrong or if the same OpenAPI spec can be used in multiple environments.

This solution instead creates a default environment with two variables "protocol" and "host", which are filled according to the previously constructed default baseUrl. This makes it very easy to change for all requests while preserving the server information extracted from the spec.

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [ ] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

2024-03-18 03:39 UTC, nikolaihen commented
Any updates on getting this merged...? 

This is a pain when working with large APIs with different environments...

2024-03-27 22:17 UTC, bSolt requested changes
Your solution is not any better than the way it currently works. I need the whole host to come from a variable, and your solution would break that. You can just replace your hosts in your collection this way with your own script if you need it. That's what I ended up doing anyway

2024-03-27 22:23 UTC, AndrejsK commented
Right, but this way you can change it through the UI, that's better than writing a script, if you ask me. Would you be happy with this PR if the whole base url was a single variable?

2024-05-16 17:06 UTC, TheBlackReverand commented
I make a PR with my proposition #2088 with that you can create and describe multiple environment.

2024-10-14 06:48 UTC, closed without merging

2024-10-14 06:48 UTC, helloanoop commented
Closing this PR as this has been addressed in #3267