fix(generate-code): fixing generate code issue where headers from collections are not being reflected
usebruno/bruno pull request #1246
Opened 2023-12-19 10:39 UTC by DivyMohan14

…

# Description

This PR fixes the generate code issue where headers from collections are not being reflected upon generating code

### Contribution Checklist:

- [X] **The pull request only addresses one issue or adds one feature.**
- [X] **The pull request does not introduce any breaking changes**
- [ ] **I have added screenshots or gifs to help explain the change if applicable.**
- [X] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [X] **Create an issue and link to the pull request.**

2024-01-14 21:31 UTC, Its-treason requested changes
Hey, I just looked over your merge request, and it's not quite right.

You are using the headers from `item.requestSent.headers` but this is only set after sending a request.

The collection headers are stored in `collection.root.request.headers` and can be merged with the normal request headers. I added some code suggestion, with my idea.

2024-01-14 21:31 UTC, Its-treason commented on packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/GenerateCodeItem/index.js
> +                          headers: headers
```suggestion
                          url: interpolatedUrl,
                          headers: [...item.request.headers, ...collection.root.request.headers],
```
Merge request headers with collection headers here

2024-01-14 21:31 UTC, Its-treason commented on packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/GenerateCodeItem/index.js
> +                          headers: headers
```suggestion
                          url: interpolatedUrl,
                          headers: [...item.draft.request.headers, ...collection.root.request.headers],
```
Merge request headers with collection headers here

2024-01-14 21:31 UTC, Its-treason commented on packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionItem/GenerateCodeItem/index.js
> +
```suggestion
```
Not need anymore

2024-01-15 05:28 UTC, DivyMohan14 commented
@Its-treason thanks for the review. The only reason I wanted to stick with items was to make sure any new additions do not cause this piece to break again. But given that we only have collections for now, I think this is a good idea.
Thanks and please re-review

2024-01-15 17:28 UTC, Its-treason reviewed
So I just saw this PR has been merged: https://github.com/usebruno/bruno/pull/1316 that does the same thing as this PR. 

So This PR might be obsolete, sorry I put you through the hassle of making review changes, I should have seen the other PR earlier

2024-07-03 13:06 UTC, closed without merging