created yaml issue templates
usebruno/bruno pull request #1426
Opened 2024-01-21 14:51 UTC by yaten2302

# Description

fixes #1422 

This is a PR for creating custom `yaml` issue templates. The templates added are - `Bug Report`, `Feature Request` along with the link of the discussions and discord server.

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

2024-01-22 20:20 UTC, Its-treason requested changes
Hey, I think this is a good start, but I think the wording can be improved. I added some suggestions.

2024-01-22 20:20 UTC, Its-treason commented on .github/ISSUE_TEMPLATE/BugReport.yaml
> +  - type: checkboxes
I think it would be better if we move these checkboxes up to the top

2024-01-22 20:20 UTC, Its-treason commented on .github/ISSUE_TEMPLATE/BugReport.yaml
> +      description: Add some screenshots(if applicable) to help explain the problem.
I don't think we need the `(if applicable)` here

2024-01-22 20:20 UTC, Its-treason commented on .github/ISSUE_TEMPLATE/BugReport.yaml
> +      descripiton: Add .bru file(if applicable) here of the bug.
`descripiton` has a typo

I would change the description to something like: `Attach your .bru file here that can reqroduce the problem`

2024-01-22 20:20 UTC, Its-treason commented on .github/ISSUE_TEMPLATE/FeatureRequest.yaml
> +  - type: checkboxes
Same as above, move checkboxes to the top

2024-01-22 20:20 UTC, Its-treason commented on .github/ISSUE_TEMPLATE/config.yaml
> +    about: Please ask/answer your questions or give the feedback here.
I think writing `You can ask general questions or give feadbeck here` sounds better.

2024-01-22 20:20 UTC, Its-treason commented on .github/ISSUE_TEMPLATE/config.yaml
> +    about: Please join the discord server for furthur clarification of your query or feedback.
Maybe writing `Join our Discord community to chat about Bruno` here makes it clearer.

2024-01-24 05:09 UTC, yaten2302 commented
Hey @Its-treason, made the changes, could you please review 👍

2024-02-07 05:58 UTC, yaten2302 commented
Hey @Its-treason, any update on this PR :)

2024-02-09 17:56 UTC, Its-treason approved these changes
I think we could also take a look at this in the community call on 14 Feb.

2024-04-06 00:41 UTC, merged

2024-04-06 00:42 UTC, helloanoop commented
Merged! Thanks @yaten2302 !
Thanks for the review @Its-treason