fix(#1532) - fix default bearer token 'undefined'
usebruno/bruno pull request #1533
Opened 2024-02-07 10:24 UTC by SoulKa

# Description

Fix for #1532

Using an empty string as default Bearer Token on new requests instead of `undefined`:

![image](https://github.com/usebruno/bruno/assets/15342503/c50258c9-9b90-4423-bebe-6d5708efd3de)

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

2024-02-11 17:05 UTC, Its-treason requested changes

2024-02-11 17:05 UTC, Its-treason commented on packages/bruno-app/src/components/RequestPane/Auth/BearerAuth/index.js
> +  const bearerToken =
This does work, but I don't think it's a "fancy" solution. How about giving get a default value?

```suggestion
  const bearerToken = item.draft
    ? get(item, 'draft.request.auth.bearer.token', '')
    : get(item, 'request.auth.bearer.token', '');
```

2024-02-19 10:48 UTC, Its-treason approved these changes

2024-07-01 07:22 UTC, sanjai0py commented
Thanks for the PR, @SoulKa, but another PR has fixed the code. 

https://github.com/usebruno/bruno/blob/fd57b2ce94b072b7503b24f276edaef02bd0c29f/packages/bruno-app/src/components/RequestPane/Auth/BearerAuth/index.js#L14-L16 

Closing the PR.

2024-07-01 07:22 UTC, closed without merging