renamed Remove & altered popover description
usebruno/bruno pull request #1538
Opened 2024-02-07 13:27 UTC by eugen-soliar

# Description

- Renamed 'Remove' button in dropdown menu.
- Altered description in popover dialog accordingly.
Fixes [1009](https://github.com/usebruno/bruno/issues/1009)

![CloseCollection](https://github.com/usebruno/bruno/assets/123383924/e98606a9-5b64-4466-a889-899999ac2e57)
![CloseCollectionPopup](https://github.com/usebruno/bruno/assets/123383924/572aee1b-b649-4ce5-a756-d1adf9ed2dc6)

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

2024-02-07 16:06 UTC, Its-treason requested changes
I think we should change the naming here, but I'm not sure if "disconnect" is the best wording, how about "close"? I'm not entirely sure about this, but I never saw something like this named "disconnect".

2024-02-07 16:06 UTC, Its-treason commented on packages/bruno-app/src/components/Sidebar/Collections/Collection/RemoveCollection/index.js
>      <Modal size="sm" title="Remove Collection" confirmText="Remove" handleConfirm={onConfirm} handleCancel={onClose}>
The title and confirmText should also be updated

2024-02-07 16:06 UTC, Its-treason commented on packages/bruno-app/src/components/Sidebar/Collections/Collection/RemoveCollection/index.js
> +      Bruno? It will remain in your file system anyways.
I think the last sentence sounds weird with the "anyways". How about: "The collection files will remain in your file system in [Collection Path here]"

2024-02-13 22:12 UTC, merged

2024-02-13 22:26 UTC, helloanoop commented
Merged! Thank you @eugen-soliar !
Thanks for the review @Its-treason !

I also made some small UX updates
![image](https://github.com/usebruno/bruno/assets/9350733/4850e8f4-fa94-4a50-8759-578937a63a2d)