feat: make `BrunoResponse` callable to access body data using expressions fixes (#481)
usebruno/bruno pull request #3710
Opened 2024-12-30 08:05 UTC by Pragadesh-45

fixes: #481 

# Description

This PR introduces the ability to use the `res` object as a callable function to access body data directly. For example:  

```javascript
const page = res('page');
```

This functionality simplifies post-response scripting. Currently, developers has a  workaround:  

```javascript
const { get } = require('lodash');
const page = get(res.getBody(), 'page');
console.log('page', page);
```

With this PR, the `res` object can now be used both as an object and as a function, providing a more convenient way to scripts.
### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

2024-12-31 23:33 UTC, Kenttleton requested changes

2024-12-31 23:33 UTC, Kenttleton commented on packages/bruno-js/src/bruno-response.js
> +    return get(this.res.data, expr, ...fns);
This doesn't satisfy the full feature. lodash.get does not support array filtering.

2024-12-31 23:33 UTC, Kenttleton commented on packages/bruno-js/src/bruno-response.js
> +    return get(this.res.data, expr, ...fns);
This would be better off using JSONPath instead of lodash.

2024-12-31 23:38 UTC, Kenttleton commented
Check out the examples given in the [docs](https://docs.usebruno.com/testing/script/response/response-query). The solution should satisfy the example inputs and outputs as written.

2025-01-02 05:08 UTC, Pragadesh-45 commented
@Kenttleton Thanks for your valuable input. I will update this PR

2025-01-02 05:14 UTC, Kenttleton commented
I recommend using the JSONPath library instead of lodash as it gets you most of the way there. This lib is also used in Bruno to filter responses and has a similar syntax as the docs. Don't forget to add an optional callback to the signature for further refinements and please provide test cases for your implementation.

2025-01-03 15:00 UTC, ramki-bruno approved these changes

2025-01-28 09:27 UTC, merged