Feat : added feature to close the active tab with middle mouse click #485
usebruno/bruno pull request #514
Opened 2023-10-10 15:23 UTC by Sahilm416

-Added the functionality to close the active tab with middle mouse click
-Middle click functionality is added inside the whole main section

2023-10-10 21:14 UTC, helloanoop requested changes

2023-10-10 21:14 UTC, helloanoop commented on packages/bruno-app/src/components/RequestTabPanel/index.js
> +      <section className="main flex flex-grow pb-4 relative" onMouseDown={(e) => MiddleClickClose(e)}>
Please rename `MiddleClickClose` as `handleMouseDown`

You can add a comment in the callback like this.
You also don't have to write an explicit return.
 
```javascript
const handleMouseDown = (e) => {
  // middle click
  if (e.button === 1) {
    handleCloseClick(e, focusedTab, dispatch);
  }
};
```

2023-10-10 21:14 UTC, helloanoop commented on packages/bruno-app/src/components/RequestTabPanel/index.js
> +import { handleCloseClick } from 'components/RequestTabs/RequestTab/index';
Let'd not wire components like this.
You need to use a redux action.

2023-10-10 21:16 UTC, helloanoop commented
Also @Sahilm416 We have a functionality where - if a user is editing something, upon clicking in close we show an alert modal requesting to either save or cancel the draft.

The middle click implementation should ensure that this flow is not broken.

2023-10-11 04:01 UTC, Sahilm416 commented
Thanks for the review !

2023-10-12 02:52 UTC, closed without merging