feat: Create New Request e2e test
usebruno/bruno pull request #52
Opened 2022-10-28 10:18 UTC by depapp

this PR consists of:
- add selector ID
- include an e2e test for the `Create New Request` flow

2022-10-29 12:58 UTC, helloanoop commented
@depapp Thanks for the PR !
I have one comment.

2022-10-30 05:06 UTC, depapp commented
> @depapp Thanks for the PR !
> 
> I have one comment.

@helloanoop I don't see any comment from you

2022-10-30 10:01 UTC, helloanoop requested changes

2022-10-30 10:01 UTC, helloanoop commented on tests/pages/home.page.js
> +    this.methodName = page.locator('.flex > .StyledWrapper__Wrapper-sc-1tpbhjh-0 > .flex').first();
@depapp Can we update the selector here ?
I recommend not to use the `StyledWrapper__Wrapper-sc-1tpbhjh-0` auto generated class

2022-10-31 05:21 UTC, depapp commented on tests/pages/home.page.js
> +    this.methodName = page.locator('.flex > .StyledWrapper__Wrapper-sc-1tpbhjh-0 > .flex').first();
@helloanoop updated

2022-10-31 11:20 UTC, merged

2022-10-31 11:21 UTC, helloanoop commented
Awesome ! Merged.
Thanks @depapp